define(() => [
	'Irina Aime',
	'Alejo Amillano',
	'Santi Bello',
	'Magdalena Cernadas',
	'Agus Cseh',
	'Agus Cutre',
	'Cami De Paul',
	'Agnes Dormal',
	'Manu Firpo',
	'Cami Forletta',
	'Maitena Galindez',
	'Delfi Giesenow',
	'Alejo Gonzalez',
	'Juan Huidobro',
	'Franco La Mattina',
	'Agus Lalia',
	'Tomás Lopez',
	'Tiziana Maddalena',
	'Lola Marotta',
	'Tomas Molinari',
	'Maca Montoya',
	'Delfi Orlansky',
	'Trini Pardo',
	'Fini Quirno',
	'Fran Rendo',
	'Nico Riccitelli',
	'Agos Rivas',
	'Rosario Rodriguez',
	'Lucía Salas',
	'Mati Salazar',
	'Mati Tena',
	]
);
